- src/toxcore/dht_new/codec.rs
- src/toxcore/dht_new/kbucket.rs
- src/toxcore/dht_new/mod.rs
- src/toxcore/dht_new/packed_node.rs
- src/toxcore/dht_new/packet.rs
- src/toxcore/dht_new/packet_kind.rs
Refactor codec.rs for UDP packet.
> refactor codec.rs

- src/toxcore/dht_new/packet.rs
apply new DhtPacketPayload::from_bytes() to get_payload() of dht_impl.rs.
This PR has rebased on #11
> Add DhtPacket::get_payload

- Cargo.toml
To display win build status correctly
> fix(cargo): fix Appveyor badge on crates.io

- Cargo.toml
- src/lib.rs
- src/toxcore/dht/server.rs
- src/toxcore/tcp/server/server.rs
parking_lot::RwLock has one good property:
> RwLock uses a task-fair locking policy, which avoids reader and writer starvation, whereas the standard library version makes no guarantees.
It will be important for onion - no matter how many read locks we have we want to force refresh key when time is come.
> refactor: use parking_lot::RwLock

- .gitlab-ci.yml
It is necessary for run the assembly, testing and documentation on the Windows platform.
> feat(gitlab): added job for build with windows

- src/toxcore/dht/dht_friend.rs
- src/toxcore/dht/dht_node.rs
- src/toxcore/dht/kbucket.rs
- src/toxcore/dht/server/client.rs
- src/toxcore/dht/server/hole_punching.rs
- src/toxcore/dht/server/mod.rs
DhtNode has redundancy in peers_cache.
So, separate ClientData from DhtNode.
> separate ClientData from DhtNode

- Cargo.toml
- examples/dht_server.rs
- src/lib.rs
- src/toxcore/dht/codec.rs
There are two ways to fix handling of incomplete or broken packet:
1. Encode deserialization error type to `Decoder::Item` and then filter out these error. In this approach we should change `type Item = DhtPacket;` to `type Item = Result<DhtPacket, Err>;` in `impl Decoder for DhtCodec` and return `Ok(Err(...))` in `decode` method in case of failure.
2. Add possibility to match on error types so that we could filter out only deserialization errors. This is  a bit more straightforward approach but requires to change error types. The easiest way to do it is using `failure` crate. It will bring some mess with errors in our code but if we are going to customize our errors it could be a good starting point.
This pull request implements the second way. Thoughts?
> Do not fall on invalid packets

- examples/dht_server.rs
- src/toxcore/binary_io.rs
- src/toxcore/dht/lan_discovery.rs
- src/toxcore/dht/mod.rs
- src/toxcore/dht/server/hole_punching.rs
- src/toxcore/dht/server/mod.rs
- src/toxcore/dht/server/ping_sender.rs
- src/toxcore/io_tokio.rs
- src/toxcore/net_crypto/mod.rs
This PR:
- implements advanced LAN discovery from `friend_connection.c`
- moves onion key refreshing to `dht_main_loop`
- simplifies dht_server example
I decided to leave LAN discovery wake ups separated from `dht_main_loop` since:
- it'd have required adding additional argument to server
- LAN discovery is optional so if it's disabled we don't need LAN wake ups at all (at least in bootstrap server).
> DHT refactoring

- src/toxcore/dht/server/mod.rs
The work to separate LanDiscovery is already done by Evegeny.
I make processing of LanDiscovery optional.
> make LanDiscovery optional

- src/toxcore/dht/dht_friend.rs
Number of friend's close nodes was limited to 4 by mistake. Bootstrap nodes list should be limited instead.
> Limit bootstrap nodes of friend instead of close nodes

- src/toxcore/dht/daemon_state.rs
- src/toxcore/dht/dht_node.rs
- src/toxcore/dht/kbucket.rs
- src/toxcore/dht/server/mod.rs
Changes:
- Since `Bucket` stores only nodes that we can reach `DhtNode` can have IPv6 address only if `is_ipv6_enabled` is `true`. It means that we don't have to pass this variable to `DhtNode` and store it in `Kbucket` anymore. So it was removed.
> Simplify dht node

- src/toxcore/crypto_core.rs
Because of https://github.com/TokTok/c-toxcore/issues/1169
> feat(crypto_core): dont validate PublicKey when parsing

- src/toxcore/tcp/connections/connections.rs
I cannot find a way to fix in correctly, so let's disable this test and fix it later. To not block other PRs like #245.
> fix(tcp): temporary disabled hanging tcp test

- src/toxcore/tcp/handshake/mod.rs
https://travis-ci.org/tox-rs/tox/jobs/462781101#L1508
The same port was used twice.
> Fix 'Address already in use' error

- examples/tcp_server.rs
- src/toxcore/tcp/client/client.rs
- src/toxcore/tcp/server/server.rs
- src/toxcore/tcp/server/server_ext.rs
Tested with `ulimit -n 64`, running with limit of 32 connections and spawning with `for i in {1..100}; (netcat localhost 33445 &);`.
> Add limit for TCP connections count

- src/toxcore/crypto_core.rs
- src/toxcore/dht/server/mod.rs
Later it will be used to choose random nodes for onion paths
> Add function for unbiased random numbers

- src/toxcore/dht/lan_discovery.rs
- src/toxcore/dht/server/mod.rs
- src/toxcore/io_tokio.rs
- src/toxcore/net_crypto/mod.rs
- src/toxcore/tcp/server/client.rs
Get rid of `send_bounded` functions and move timeouts to loops. This gives us:
- Less complicated error types which fixes 2 clippy warnings
- Less timers being initialized which should increase performance a bit.
Also this PR makes timeout all error not critical so they won't terminate the application.
> Refactor timeouts

- Cargo.toml
- src/toxcore/crypto_core.rs
- src/toxcore/dht/packet/crypto_data.rs
- src/toxcore/state_format/old.rs
Fixes #388.
This favors the `x::from_yy_bytes` functions instead of using the `byteorder` crate. This crate is removed as a dependency.
There was a single use of `NativeEndian` from `byteorder`, when generating random numbers. This was replaced with a use of `from_be_bytes` instead. This has no semantic differences, but *might* be a bit slower on little endian platforms.
The changes were otherwise straightforward.
> refactor: Replace byteorder with std functions

- src/toxcore/stats.rs
Fixes #360
Previously, we wanted to use `AtomicUsize` as an atomic type large enough for a 64 bit counter. This meant having two versions of the code, one with atomics, another with locks. With the introduction of `AtomicU64` into stable, we can simply use this type no matter what.
This removes code duplication, and allows us to avoid using locks on platforms with 32 bit usize.
> refactor(stats): Use AtomicU64 instead of locks

- src/toxcore/dht/dht_friend.rs
- src/toxcore/dht/dht_node.rs
- src/toxcore/dht/kbucket.rs
- src/toxcore/dht/ktree.rs
- src/toxcore/dht/lan_discovery.rs
- src/toxcore/dht/server/hole_punching.rs
- src/toxcore/dht/server/mod.rs
- src/toxcore/friend_connection/mod.rs
- src/toxcore/onion/client/mod.rs
- src/toxcore/onion/client/paths_pool.rs
- src/toxcore/onion/onion_announce.rs
- src/toxcore/tcp/client/connections.rs
- src/toxcore/tcp/server/client.rs
- src/toxcore/tcp/server/server.rs
- src/toxcore/tcp/server/server_ext.rs
This prevents misusing them as plain numbers.
> refactor(toxcore): Replace intervals as bare `u64`s with `Duration`s

- tox_crypto/src/lib.rs
- tox_encryptsave/src/lib.rs
Uses the sodiumoxide API from the [documentation example](https://docs.rs/sodiumoxide/0.2.5/sodiumoxide/crypto/pwhash/index.html#example-key-derivation) for deriving
a key from a passphrase, and securely zeroing the intermediate key.
> Use idiomatic sodiumoxide API for password KDF

- examples/dht_server.rs
- examples/echo.rs
- examples/onion_client.rs
- examples/tcp_server.rs
- tox_core/src/dht/lan_discovery.rs
- tox_core/src/friend_connection/mod.rs
- tox_core/src/onion/client/mod.rs
- tox_core/src/relay/client/connections.rs
It became possible after migration to async/await.
> refactor: remove unnecessary clones and async move blocks

- .github/workflows/rust.yml
- README.md
- tox_core/Cargo.toml
- tox_core/src/dht/forced_ktree.rs
- tox_core/src/dht/mod.rs
- tox_core/src/dht/server/mod.rs
- tox_core/src/net_crypto/crypto_connection.rs
- tox_core/src/relay/client/client.rs
- tox_packet/src/toxid.rs
Unlike k-tree it holds additional 8 nodes that are always closest to
own PK. It forces a peer to always accept nodes that are closer than
known ones which improves search time.
> feat(ktree): implement k-tree with force-k modification

- examples/dht_server.rs
- examples/echo.rs
- tox_core/src/dht/server/mod.rs
- tox_core/src/dht/server_ext.rs
- tox_core/src/friend_connection/mod.rs
- tox_core/src/lib.rs
- tox_core/src/onion/client/mod.rs
- tox_core/src/udp.rs
It helps to avoid dependency cycle DHT -> OnionClient -> DHT.
> refactor(dht): split dht to dht and udp structs

- tox_core/src/dht/daemon_state.rs
- tox_core/src/dht/server/mod.rs
- tox_core/src/onion/client/mod.rs
This should fix a deadlock we currently have on master. Later we can
move more stuff in this state and make it pure version of DHT server.
> refactor(dht): introduce a single DHT server state

- tox_core/src/relay/server/client.rs
- tox_core/src/relay/server/server.rs
Currently we send tcp packets while holding the state lock. At the
same time we use bounded queues for sending of packets. This means
that a single stuck client can block the whole server until the
timeout happens. This change makes the server release the state lock
before sending any packet.
> refactor(tcp_server): release state lock before sending packets
