tox-rs/tox

- examples/tcp_server.rs
- src/toxcore/tcp/codec.rs
- src/toxcore/tcp/packet.rs
- src/toxcore/tcp/server/client.rs
- src/toxcore/tcp/server/server.rs
> TCP onion packets

- src/toxcore/dht_new/packet.rs
> test(dht): add test for DhtRequest encoding/decoding

- src/lib.rs
Fix https://travis-ci.org/tox-rs/tox/jobs/343079381#L1082  https://ci.appveyor.com/project/kpp/tox/build/1.0.200
> fix(dht): disable DHT example from lib.rs

- src/toxcore/onion/mod.rs
- src/toxcore/onion/packet.rs
> Improve onion docs according to #37

- src/toxcore/dht/codec.rs
- src/toxcore/dht/packet.rs
Add test case for codec.rs
Remove duplicated test case of packet.rs
> Codec test

- src/toxcore/dht/client.rs
- src/toxcore/dht/kbucket.rs
- src/toxcore/dht/mod.rs
- src/toxcore/dht/packed_node.rs
- src/toxcore/dht/packet.rs
- src/toxcore/dht/server.rs
Revise comments for docs.
- packet.rs
- packed_node.rs
- client.rs
- kbucket.rs
- mod.rs
- server.rs
> Revise DHT docs

- src/toxcore/dht/client.rs
- src/toxcore/dht/codec.rs
- src/toxcore/dht/kbucket.rs
- src/toxcore/dht/packed_node.rs
- src/toxcore/dht/packet.rs
- src/toxcore/dht/server.rs
Fix warnings produced by clippy
> fix(dht): fix warnings using clippy

- examples/dht_node.rs
- src/toxcore/dht/server.rs
Move from tokio-core to tokio.
Now server.rs is multithreaded.
> Move to tokio

- Cargo.toml
- examples/dht_node.rs
- src/lib.rs
- src/toxcore/dht/client.rs
- src/toxcore/dht/server.rs
> feat(dht): lan discovery handler

- examples/dht_node.rs
- src/toxcore/dht/client.rs
- src/toxcore/dht/server.rs
The reason of error is socket does not have right to send broadcast addresses.
TODO:
Closes #76
Socket can listen both ipv4 and ipv6 at the same time.
But socket can send packet only one ip-type.
so listening on both type.
separated socket is used to send packet.
> fix(dht): Lan discovery permission denied

- src/toxcore/crypto_core.rs
- src/toxcore/onion/mod.rs
- src/toxcore/onion/onion_announce.rs
- src/toxcore/onion/packet/announce_response.rs
> Implement OnionAnnounce struct

- examples/dht_node.rs
It's not guaranteed for future that it will start computation if we just drop it. So we have to return the same future from closure that we got from handle_packet function.
> fix(dht): handle server result properly

- examples/dht_node.rs
- src/toxcore/dht/client.rs
- src/toxcore/dht/server.rs
Remove clients which is timed-out for 182 seconds
> feat(dht): remove timed out clients

- src/toxcore/dht/server.rs
> Handle DhtRequest properly

- src/toxcore/onion/onion_announce.rs
See https://github.com/TokTok/c-toxcore/pull/607
> Increase onion ping id timeout

- examples/dht_node.rs
- src/toxcore/dht/server/client.rs
- src/toxcore/dht/server/mod.rs
> Add hash of pings to DHT server

- examples/dht_node.rs
- src/toxcore/dht/dht_friend.rs
- src/toxcore/dht/server/hole_punching.rs
- src/toxcore/dht/server/mod.rs
Because of absent of friend connection functions, this PR does not include testings related NatPingResponse.
> Hole Punch and NatPing

- examples/dht_server.rs
- src/toxcore/dht/dht_node.rs
- src/toxcore/dht/kbucket.rs
- src/toxcore/dht/server/mod.rs
- src/toxcore/dht/server/ping.rs
- src/toxcore/dht/server/ping_sender.rs
Current implementation of Ping is not correct.
This PR is fixing it.
> add Ping iterator

- src/toxcore/dht/dht_friend.rs
- src/toxcore/dht/dht_node.rs
- src/toxcore/dht/kbucket.rs
- src/toxcore/dht/server/hole_punching.rs
- src/toxcore/dht/server/mod.rs
https://zerhoinfo.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=SL&modal=detail&selectedIssue=SL-237
I think SL - 237 is for this PR
> Hole punch: take address of friend they returned

- src/toxcore/net_crypto/mod.rs
See https://ci.appveyor.com/project/kpp/tox/build/1.0.2136#L896
> Avoid problems with floating point arithmetic

- src/toxcore/dht/server/mod.rs
- src/toxcore/onion/onion_announce.rs
Changes:
- `OnionAnnounce` uses `Server::get_closest` now to get close nodes from all possible sources.
> Refactor onion to use Server::get_closest

- src/toxcore/tcp/server/server_ext.rs
Client can be shutdown twice - first time because of timeout and second time after socket is closed. So in case of timeout we will get error.
We already ignore shutdown errors inside `TcpServer` anyway.
> Ignore client shutdown errors

- .travis.yml
Speed up TravisCI:
before: Ran for 33 min 4 sec, Total time 1 hr 42 min 25 sec
after: Ran for 23 min 10 sec Total time 1 hr 18 min 6 sec
> chore(ci): improve TravisCI

- src/toxcore/net_crypto/crypto_connection.rs
It failed again https://ci.appveyor.com/project/tox-rs/tox/builds/21674176/job/r6ctwkmeba2ixfui#L1176
> Relax test condition even more

- examples/dht_server.rs
> Fix clippy warnings in examples

- src/toxcore/dht/server/mod.rs
It's a bug introduced in `c-toxcore` after `assocs` refactoring. See the original code: https://github.com/irungentoo/toxcore/blob/bf69b54f64003d160d759068f4816b2d9b2e1e21/toxcore/DHT.c#L1740-L1763
Also see https://github.com/TokTok/c-toxcore/pull/1310
> Do not send the same packet to the same node twice

- src/toxcore/friend_connection/packet/friend_requests.rs
- src/toxcore/onion/packet/friend_request.rs
- src/toxcore/onion/packet/mod.rs
- src/toxcore/onion/packet/onion_data_response.rs
The location of this file may be changed later
> Add ser/de of FriendReq

- src/toxcore/onion/onion_client.rs
- src/toxcore/onion/request_queue.rs
Add function to check if we need to send ping.
function name is `is_redundant_ping`
> Good to ping

- src/toxcore/tcp/client/connections.rs
We should send them to our friends.
> Add function to get random relays we are connected to

- src/toxcore/net_crypto/mod.rs
Also added optional IP address to `add_connection` as it might be known at the moment we add new connection.
> Add function to set friend's IP address

- src/toxcore/net_crypto/crypto_connection.rs
- src/toxcore/net_crypto/mod.rs
We don't need it once connection is established. Only shared secret matters.
> Do not store peer_session_pk

- examples/echo.rs
- src/toxcore/onion/client/mod.rs
resolves #379 
I completely removed the hardcoded keys and the current implementation just accepts all friend requests (ignoring non spam, etc.)
> refactor(friends) remove hardcoded keys in example/echo.rs

- Cargo.toml
For https://github.com/tokio-rs/tokio/issues/1510
> Temporary fix for tokio-rs/tokio/issues/1510

- src/toxcore/dht/lan_discovery.rs
- src/toxcore/dht/server/hole_punching.rs
- src/toxcore/onion/onion_announce.rs
Followup to #407. Some comments were poorly edited. This PR fixes it.
> chore(toxcore): fix comments about durations

- examples/echo.rs
It's required by qtox now to make friend online.
> fix(examples): send userstatus from echo server

- tox_core/src/dht/server/mod.rs
- tox_core/src/onion/client/mod.rs
- tox_core/src/onion/onion_announce.rs
- tox_crypto/src/lib.rs
- tox_packet/src/onion/onion_announce_response.rs
Fixes https://github.com/tox-rs/tox/issues/387
> refactor(onion): use plain array when type of stored value isn't known
